name: Version Bump

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'Bump version') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Determine version bump
        id: determine_bump
        run: |
          # Check commit messages since last version bump
          COMMITS=$(git log $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD~10)..HEAD --pretty=format:"%s")
          
          # Check for breaking changes (major)
          if echo "$COMMITS" | grep -qE '^BREAKING CHANGE:|^feat.*!:'; then
            echo "bump=major" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for features (minor)
          if echo "$COMMITS" | grep -qE '^feat:'; then
            echo "bump=minor" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Default to patch for bug fixes and other changes
          echo "bump=patch" >> $GITHUB_OUTPUT
      
      - name: Bump version
        run: |
          # Only bump if there are changes that warrant it
          if [ "${{ steps.determine_bump.outputs.bump }}" != "" ]; then
            npm version ${{ steps.determine_bump.outputs.bump }} -m "Bump %s [skip ci]"
            git push
            git push --tags
          else
            echo "No version bump needed"
          fi 